export const CONSTRUCTOR_ADD_ITEM: 'CONSTRUCTOR_ADD_ITEM' = 'CONSTRUCTOR_ADD_ITEM';
export const CONSTRUCTOR_DELETE_ITEM : 'CONSTRUCTOR_DELETE_ITEM' = 'CONSTRUCTOR_DELETE_ITEM';

export const CONSTRUCTOR_RESORT : 'CONSTRUCTOR_RESORT' = 'CONSTRUCTOR_RESORT';
